name: flutter_app
description: A new Flutter application.


publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"


dependencies:
  simple_animations: ^2.5.1
  flutter_svg: ^0.17.1
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_database: ^6.1.0
  google_sign_in: ^4.5.1
  provider: ^4.3.2+2
  http: ^0.13.0
  webview_flutter: ^0.3.18+1
  google_maps_flutter: ^2.0.1
  csv:  ^4.1.0
  geolocator: ^7.0.1



  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: GlacialIndifference
      fonts:
        - asset: fonts/GlacialIndifference-Regular.otf
        - asset: fonts/GlacialIndifference-Bold.otf
          weight: 700
        - asset: fonts/GlacialIndifference-Italic.otf
          style: italic
    - family: MyFlutterApp
      fonts:
          - asset: fonts/MyFlutterApp.ttf

  uses-material-design: true

  assets:
    - images/
    - EateryData/
#    - images/loginui.png
#    - images/loginbottom.png
#    - images/homepage.png
#    - images/cutlery.svg
#    - images/chefhat.svg
#    - images/testPic.png
#    - images/appbar_recipe.png
#    - images/appbar_eatery.png
#    - images/google_logo.png
#    - images/a_dot_ham.jpeg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
